<a href="https://colab.research.google.com/github/josejailson/feature_engineering/blob/main/feature_enginering.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
from google.colab import files

files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"jailsonjunior314","key":"64dc0f2a81969ddfe33849b759eabf40"}'}

In [ ]:
from sklearn.

In [ ]:
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json


In [ ]:
!kaggle competitions download titanic

  0% 0.00/34.1k [00:00<?, ?B/s]
100% 34.1k/34.1k [00:00<00:00, 52.8MB/s]


In [ ]:
!unzip *.zip && rm *.zip

Archive:  titanic.zip
  inflating: gender_submission.csv   
  inflating: test.csv                
  inflating: train.csv               


In [ ]:
import pandas as pd
import numpy as np

data = pd.read_csv("train.csv")
X = data.drop("Survived", axis=1)
y = data["Survived"].copy()

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder


num_pipeline = make_pipeline(SimpleImputer(strategy="median"), StandardScaler())
cat_pipeline = make_pipeline(SimpleImputer(strategy="most_frequent"), OneHotEncoder(handle_unknown="ignore", sparse_output=False))

preprocessing = make_column_transformer(
    (num_pipeline, make_column_selector(dtype_include = np.number)),
    (cat_pipeline, make_column_selector(dtype_include = object)),
)

In [ ]:
from sklearn.feature_selection import SelectFromModel
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier

naive = GaussianNB()
estimator = RandomForestClassifier()
selector = SelectFromModel(estimator)
model = make_pipeline(preprocessing, selector, naive)


model.fit(X, y)


Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f30f08dd660>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f30f08dd420>)])),
                ('selectfrommodel',
                 SelectFromModel(estimator=RandomForestClassifier())),
                ('gaussiannb', GaussianNB())])

In [ ]:
test = pd.read_csv("test.csv")

y_pred = model.predict(test)

In [ ]:
result = pd.read_csv("gender_submission.csv")

In [ ]:
result = pd.read_csv("gender_submission.csv")
result["Survived"] = y_pred
result.to_csv("resu.csv", index=False)

In [ ]:
result.to_csv("resu.csv", index=False)

In [ ]:
a = selector.get_support()

In [ ]:
for value in a:
  print(value)

In [ ]:
selector.get_support()

array([ True, False,  True, False, False,  True])

In [ ]:
from sklearn.ensemble import RandomForestRegressor
from sklearn.datasets import fetch_california_housing

from sklearn.feature_selection import SelectFromModel

# Carregar o conjunto de dados de exemplo
housing = fetch_california_housing()
X = housing.data
y = housing.target

# Criar um estimador baseado em RandomForestClassifier
estimator = RandomForestRegressor()

# Criar a instância SelectFromModel com o estimador
selector = SelectFromModel(estimator)

# Aplicar a seleção de características
X_new = selector.fit_transform(X, y)

# Verificar as características selecionadas
print(selector.get_support())  # Retorna um array booleano indicando as características selecionadas
print(X_new)  # Retorna os dados com as características selecionadas

[ True False False False False  True False False]
[[8.3252     2.55555556]
 [8.3014     2.10984183]
 [7.2574     2.80225989]
 ...
 [1.7        2.3256351 ]
 [1.8672     2.12320917]
 [2.3886     2.61698113]]


In [ ]:
housing.feature_names

['MedInc',
 'HouseAge',
 'AveRooms',
 'AveBedrms',
 'Population',
 'AveOccup',
 'Latitude',
 'Longitude']

In [ ]:
from sklearn.datasets import fetch_california_housing

from sklearn.feature_selection import SelectFromModel

# Carregar o conjunto de dados de exemplo
housing = fetch_california_housing(as_frame=True)

In [ ]:
housing.target.info()


<class 'pandas.core.series.Series'>
RangeIndex: 20640 entries, 0 to 20639
Series name: MedHouseVal
Non-Null Count  Dtype  
--------------  -----  
20640 non-null  float64
dtypes: float64(1)
memory usage: 161.4 KB


In [ ]:
from sklearn.neural_network import MLPClassifier

mlp = MLPClassifier([50, 50, 50])

In [ ]:
from sklearn.linear_model import SGDClassifier

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder


num_pipeline = make_pipeline(SimpleImputer(strategy="median"),
                             StandardScaler())
cat_pipeline = make_pipeline(SimpleImputer(strategy="most_frequent"),
                             OneHotEncoder(handle_unknown="ignore",
                             sparse_output=False))

preprocessing = make_column_transformer(
    (num_pipeline, make_column_selector(dtype_include = np.number)),
    (cat_pipeline, make_column_selector(dtype_include = object)),
)

In [ ]:
estimator = RandomForestClassifier()
selector = SelectFromModel(estimator)
model = make_pipeline(preprocessing, selector, SGDClassifier())

model.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f30f0933670>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f30f0933070>)])),
                ('selectfrommodel',
                 SelectFromModel(estimator=RandomForestClassifier())),
                ('sgdclassifier', SGDClassifier())])

In [ ]:
from sklearn.model_selection import cross_val_score

cross_val_score(model, X, y, cv=5)

array([0.77094972, 0.78651685, 0.79213483, 0.80898876, 0.82022472])

In [ ]:
test = pd.read_csv("test.csv")

y_pred = model.predict(test)

In [ ]:
result = pd.read_csv("gender_submission.csv")
result["Survived"] = y_pred
result.to_csv("sgd.csv", index=False)

# Dropping out some features

In [ ]:
# X = data.drop(['Survived', 'PassengerId', 'Name', "Ticket", "Cabin", "Embarked"], axis=1)
# X = data[['Pclass', 'Sex', 'Age', 'SibSp', 'Parch', 'Fare']].copy()
X = data[['Pclass', 'Sex', 'Age', 'Parch', 'Fare']].copy()
y = data["Survived"].copy()

In [ ]:
from sklearn.impute import SimpleImputer
from sklearn.compose import make_column_transformer
from sklearn.compose import make_column_selector
from sklearn.pipeline import make_pipeline
from sklearn.preprocessing import StandardScaler, OneHotEncoder


num_pipeline = make_pipeline(SimpleImputer(strategy="median"),
                             StandardScaler())
cat_pipeline = make_pipeline(SimpleImputer(strategy="most_frequent"),
                             OneHotEncoder(handle_unknown="ignore",
                             sparse_output=False))

preprocessing = make_column_transformer(
    (num_pipeline, make_column_selector(dtype_include = np.number)),
    (cat_pipeline, make_column_selector(dtype_include = object)),
)

In [ ]:
model = make_pipeline(preprocessing, RandomForestClassifier())
model.fit(X, y)

Pipeline(steps=[('columntransformer',
                 ColumnTransformer(transformers=[('pipeline-1',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='median')),
                                                                  ('standardscaler',
                                                                   StandardScaler())]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f3131d2e6e0>),
                                                 ('pipeline-2',
                                                  Pipeline(steps=[('simpleimputer',
                                                                   SimpleImputer(strategy='most_frequent')),
                                                                  ('onehotencoder',
                                                                   OneHotEncoder(handle_unknown='ignore',
                                                                                 sparse_output=False))]),
                                                  <sklearn.compose._column_transformer.make_column_selector object at 0x7f30edd88be0>)])),
                ('randomforestclassifier', RandomForestClassifier())])

In [ ]:
cross_val_score(model, X, y, cv=4)

array([0.76233184, 0.84304933, 0.80717489, 0.82882883])

In [ ]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB
